FROM alpine:3.21

# Установка минимального набора инструментов и зависимостей
RUN apk add --no-cache \
    ostree \
    docker \
    fuse \
    fuse3

# Команда по умолчанию
CMD ["ostree", "--version"]