name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout кода из репозитория
      - uses: actions/checkout@v4

      # 2. Установка OSTree
      - name: Install OSTree
        run: |
          sudo apt-get update
          sudo apt-get install -y ostree

      # 3. Логин в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      # 4. Сборка Docker-образа
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/skywar-design/alt-atomic:source

      # 5. Загрузка Docker-образа в GitHub Container Registry
      - name: Push the Docker image to GitHub Container Registry
        run: docker push ghcr.io/skywar-design/alt-atomic:source

      # 6. Создание временного контейнера из собранного образа
      - name: Create temporary container
        run: docker create --name temp-container ghcr.io/skywar-design/alt-atomic:source

      # 7. Копирование репозитория OSTree из контейнера на хост
      - name: Copy OSTree repo from container repo
        run: docker cp temp-container:/sysroot/ostree/repo ./ostree_repo

      # 7. Копирование репозитория OSTree из контейнера на хост
      - name: Copy OSTree repo from container repo copy
        run: docker cp temp-container:/sysroot/ostree/repo ./ostree_repo_copy

      # 8. Удаление временного контейнера
      - name: Remove temporary container
        run: docker rm temp-container

      - name: Build OSTree Docker image
        run: docker build -f Dockerfile.ostree -t ostree:v2024.9 .

      - name: Use OSTree container and build image inside
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
        run: |
          docker run --rm \
          --privileged \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd):/workspace \
          -w /workspace \
          ostree:v2024.9 \
          sh -c "
            ostree checkout --repo=/workspace/ostree_repo alt/atomic /workspace/extracted_root && \
            mkdir -p /workspace/extracted_root/sysroot/ostree/repo  && \
            cp -a /workspace/ostree_repo_copy/* /workspace/extracted_root/sysroot/ostree/repo/  && \
            ls -la /workspace/extracted_root/sysroot/ostree/repo/refs/heads && \
            cat <<EOF > /workspace/extracted_root/Dockerfile
            FROM scratch
            LABEL containers.bootc=1
            COPY . /
            CMD [\"/bin/bash\"]
            EOF  && \
            docker build -t ghcr.io/skywar-design/alt-atomic:img-latest /workspace/extracted_root  && \
            echo \"${GITHUB_TOKEN}\" | docker login ghcr.io -u \"${GITHUB_OWNER}\" --password-stdin  && \
            docker push ghcr.io/skywar-design/alt-atomic:img-latest
          "