name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout кода из репозитория
      - uses: actions/checkout@v4

      # 2. Логин в GitHub Container Registry
#      - name: Log in to GitHub Container Registry
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
#
#      # 3. Сборка Docker-образа
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag ghcr.io/skywar-design/alt-atomic:source
#
#      # 4. Загрузка Docker-образа в GitHub Container Registry
#      - name: Push the Docker image to GitHub Container Registry
#        run: docker push ghcr.io/skywar-design/alt-atomic:source
#
#      # 5. Создание временного контейнера из собранного образа
#      - name: Create temporary container
#        run: docker create --name temp-container ghcr.io/skywar-design/alt-atomic:source
#
#      # 6. Копирование репозитория OSTree из контейнера на хост
#      - name: Copy OSTree repo from container
#        run: docker cp temp-container:/sysroot/ostree/repo ./ostree_repo
#
#      # 7. Удаление временного контейнера
#      - name: Remove temporary container
#        run: docker rm temp-container
#
#      # 8. Создание файла аутентификации
#      - name: Create authentication file for GHCR
#        run: |
#          echo '{"auths":{"ghcr.io":{"auth":"$(echo -n "${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}" | base64 -w 0)"}}}' > auth.json

      # 9. Установка новой версии OSTree через контейнер
      # 3. Сборка образа с OSTree
      - name: Build OSTree Docker image
        run: docker build -f Dockerfile.ostree -t ostree:v2024.9 .

      - name: Use OSTree container
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -w /workspace \
            ostree:v2024.9 \
            ostree -v
#            ostree container encapsulate --repo=/workspace/ostree_repo alt/atomic docker://ghcr.io/skywar-design/alt-atomic:image-latest \
#            --authfile /workspace/auth.json


