name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/skywar-design/alt-atomic:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Добавить для параллельных слоев
          platforms: linux/amd64
          # Включить разделение слоев
          outputs: type=registry,cache=true